### ISSUE TITLE
Base64 Error on first run

### ISSUE THREAD

**Issue by devinmm** [WardBrian/mlb-led-scoreboard#17]
Followed the setup instructions and after doing the first run I get:

```
Traceback (most recent call last):
  File "/home/pi/mlb-led-scoreboard/main.py", line 15, in <module>
    from data import Data
  File "/home/pi/mlb-led-scoreboard/data/__init__.py", line 8, in <module>
    from data.headlines import Headlines
  File "/home/pi/mlb-led-scoreboard/data/headlines.py", line 5, in <module>
    import feedparser
  File "/usr/local/lib/python3.9/dist-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```

I am running PI OS Lite 32bit with Python 3.9.2

Is there something I forgot to do?

**Comment by devinmm** [comment]
I have solved the issue, I reimaged my SD card.
The Issue was probably with feedparser install from a previous attempt to get the base project working.
